# Random function in numpy  : 
### we use it to generate a random integers ..etc to make the operations we want

In [3]:
import numpy as np

In [4]:
rng=np.random.default_rng()

In [11]:
# this will create a random number from 1 to 6 because the last number will not count
print(rng.integers(low=1,high=7,size=3)) #-> size here is responsible of the number of values that will be returned : (low-high) is not necessary

[1 1 5]


In [14]:
# what if we want to make a 2d array 
print(rng.integers(low=1,high=11,size=(3,2)))

[[ 8  1]
 [10  6]
 [ 6  5]]


In [19]:
# seed in default_rng make you save the random values that have generated to use it 
# it is like an id to your array
rng1 = np.random.default_rng(seed=3)
print(rng1.integers(0, 10, 5))

rng2 = np.random.default_rng(seed=3)
print(rng2.integers(0, 10, 5))

[8 0 1 2 1]
[8 0 1 2 1]


# Uniform function

In [27]:
# in numpy uniform function is used to generate randoom numbers (uniformally distributed)
rng4=rng.uniform(10,20)
print(rng4) # -> will return a random value in the range of 10 and 20

14.09685469230783


In [30]:
# the size in uniform 
arr=rng.uniform(0,1,5)
print(arr) #-> will return an array of 5 numbers from the range of 0 to 1

[0.72725145 0.00853105 0.3885769  0.56287499 0.75151865]


# shuffle the array randomly

In [38]:
rng5=np.random.default_rng()
array2=np.array([1,2,3,4,5])
rng.shuffle(array2)
print(array2)

[2 3 4 5 1]


# choice : to make a random choice and print it

In [47]:
rng6=np.random.default_rng()
fruits=np.array(["apple","banana","kiwi","coconut","pineapple","lemon"])

fruit_choice=rng6.choice(fruits)
print(fruit_choice)

kiwi


In [54]:
# to make an array of a random choices  
rng7=np.random.default_rng()
fruits=np.array(["apple","banana","kiwi","coconut","pineapple","lemon"])

fruit_choice=rng6.choice(fruits,size=3)

print(fruit_choice)

['coconut' 'pineapple' 'kiwi']
