# Broadcasting in numpy

#### Broadcasting allow numpy to perform operations on arrays with different shapes by virtually expending dimensions so they match the larger shape

##  why broadcasting is important :
#### faster - without loops - less memory

### compare the deminsion from the right to the left the broadcasting happen when : 
####           the two dimensions is equal or one of them equal to 1

In [1]:
import numpy as np

In [7]:
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

(1, 4)
(4, 1)


In [8]:
print(array1*array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
# look to this example too 
a=np.array([[1],[3],[5]]) # -> shape = (3,1)
b=np.array([10,20,30,40]) # -> shape = (4,)

# then will be (3,4)
# ex : 
print(a+b)

[[11 21 31 41]
 [13 23 33 43]
 [15 25 35 45]]


In [22]:
# error example 
c=np.array([[1,3,5],
           [7,8,9]]) # -> shape = (2,3)

d=np.array([10,20,30,40]) # -> shape = (4,)

# when we try to make any operation on them like + or - will cause an error  
print(c+d) # -> error

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [25]:
# another example 
array3=np.array([[1,2,3,4,5,6,7,8,9,10]])
array4= np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array3.shape) #-> (1,10)
print(array4.shape) #-> (10,1)


(1, 10)
(10, 1)


In [26]:
# so in here we can make the operations we want to make correctly
print(array3*array4) #-> will gave us an 10x10 matrix

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [27]:
print(array3/array4)

[[ 1.          2.          3.          4.          5.          6.
   7.          8.          9.         10.        ]
 [ 0.5         1.          1.5         2.          2.5         3.
   3.5         4.          4.5         5.        ]
 [ 0.33333333  0.66666667  1.          1.33333333  1.66666667  2.
   2.33333333  2.66666667  3.          3.33333333]
 [ 0.25        0.5         0.75        1.          1.25        1.5
   1.75        2.          2.25        2.5       ]
 [ 0.2         0.4         0.6         0.8         1.          1.2
   1.4         1.6         1.8         2.        ]
 [ 0.16666667  0.33333333  0.5         0.66666667  0.83333333  1.
   1.16666667  1.33333333  1.5         1.66666667]
 [ 0.14285714  0.28571429  0.42857143  0.57142857  0.71428571  0.85714286
   1.          1.14285714  1.28571429  1.42857143]
 [ 0.125       0.25        0.375       0.5         0.625       0.75
   0.875       1.          1.125       1.25      ]
 [ 0.11111111  0.22222222  0.33333333  0.44444444  0

In [28]:
print(array3+array4)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]
