# arithmetic in numpy

In [1]:
import numpy as np

In [ ]:
# scalar arithmetic
arr=np.array([1,2,3,4])

# we can (* + - % /) to the array with only one line like the following: you can replace the * with any one you want 
# also you can make the powe like this arr ** 2
arr * 3

array([ 3,  6,  9, 12])

In [ ]:
arr2=np.array([1.2,2.5,3.99])
# numpy also have vectorized math functions
np.sqrt(arr2)
np.round(arr2) #-> and so on on the math function you have in python you can use it like this 
np.floor(arr2)

np.pi #-> pi value

3.141592653589793

In [17]:
# quick exercise 
radius = np.array([1,2,3])

# pi * r**2 -> apply thid equation to all the array
np.pi * (radius**2)

array([ 3.14159265, 12.56637061, 28.27433388])

# element wise arithmetic

In [20]:
# with element wise arithmetic we can apply operationc between 2 different arrays 

arr4=np.array([1,2,3])
arr5=np.array([4,5,6])
arr4+arr5
arr4*arr5

array([ 4, 10, 18])

# comparison operation

In [ ]:
# with comparison operation we can make filtertion to the data or get boolean values from it and so on 
arr6=np.array([1,2,3,4,5,6,7,78,8,9,9,0])
arr6[arr6 > 3]  
# -> look inside the bracket we add the comparison operation we want to make and then add 
# it in the loop bracket to get the values because what will return without the array bracket is a boolean values


array([ 4,  5,  6,  7, 78,  8,  9,  9])