# Filtering in numpy :
## select specific element from an array based on a condition

In [1]:
import numpy as np 

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
print(arr[arr>3])

[4 5 6 7 8 9]


In [4]:
# if you want only to want the boolean value of some condition 
arr>3
# this will return the values in a boolean value to return as a values use it arr[arr>3]

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [9]:
print(arr[(arr>=3) | (arr<2)])

[1 3 4 5 6 7 8 9]


In [11]:
print(arr[arr%2==0])

[2 4 6 8]


In [18]:
# if you have an array before and want to make an array from the filtered data from it 
ages=np.array([[21,89,23,24,20,18,27],
                [8,90,16,44,40,15,81]])

adults=np.where(ages>=18,ages,0) #-> filter the data and the values less than 18 will return 0
adults
# the value after the ages (0) you can replace it with any value you need 

array([[21, 89, 23, 24, 20, 18, 27],
       [ 0, 90,  0, 44, 40,  0, 81]])