# slicing in numpy

In [1]:
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])


In [5]:
# to make a slicing you will make command like this : arr[start:end:step] -> keep in mind that the end index will not be with us

# let's print the first row 
arr[0]

# let's print all the rows expect the last one 
arr[0:3]

# what if we want the last one 
arr[0:4]

# what if we want the rows in the first and third rows only 
arr[0:4:2] #-> that will make us make a step by 2  - you can also write it like that arr[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [11]:
# now let's play with the columns

arr[:,0] #-> this will return all the rows to in the first column 

# what if we want all the rows in the first 3 columns 
arr[:,0:3]

# what if we want to make a step in it 

arr[:,0:4:2] #-> this will gave us the first and third column in our matrix


array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [12]:
# what if we want to reverse the matrix -> (-) gave us the ability to reverse the matrix 

arr[:,::-1] 

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])